### ISSUE TITLE
Idea: shuffle (swing)

### ISSUE THREAD

**Issue by raphaelbastide** [toboko/nudrum-drum-machine#1]
It could be really interesting to have the possibility to mix binary and ternary tracks, and to be able to precise the time between shuffled swung notes. E.g: https://www.youtube.com/watch?v=KNUxPajWRso

**Comment by toboko** [comment]
As soon as possible I will commit a better solution for polyrhythm, so ratio like 3:1 or 2:1 will be tracked better

**Comment by toboko** [comment]
New version pushed
